### ISSUE TITLE
Could not listen on [::]:30005 error

### ISSUE THREAD

**Issue by marcus-aa** [flightaware/beast-splitter#2]
The default parameter "--listen 30005:R" gives the following error;

`Could not listen on [::]:30005: open: Address family not supported by protocol`

Probably related to IPv6 configuration?

Solved by specifying localhost:

"--listen localhost:30005:R"

**Comment by mutability** [comment]
It is a warning only; you'll get this if you have a broken ipv6 configuration (resolution of the wildcard host address returns a v6 address, but your system does not support v6 sockets)
