### ISSUE TITLE
udevadm fails on package install Ubuntu 22.04.2 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by k5okc** [flightaware/beast-splitter#8]
in debian/beast-splitter.postinst

line 45 should be changed to:

/usr/bin/udevadm ...

**Comment by mutability** [comment]
Does the `|| true` not help? IIRC I added that specifically because the path was unpredictable and it's not critical that the package script kicks udevadm (you can always do it separately and/or reboot)

**Comment by k5okc** [comment]
The exact error I got:

Preparing to unpack beast-splitter_8.2_amd64.deb ...
Unpacking beast-splitter (8.2) over (8.2) ...
Setting up beast-splitter (8.2) ...
/var/lib/dpkg/info/beast-splitter.postinst: line 78: /sbin/udevadm: No such file or directory

Maybe just leave off the path and just use udevadm ...

The ```|| true``` doesn't seem to help.

**Comment by mutability** [comment]
and the postinst then _fails_?

**Comment by k5okc** [comment]
Maybe something like:

\`which udevadm` trigger --property-match="ID_USB_DRIVER=cp210x" 2> /dev/null || true

Any error message is going to make the admin stop and figure out what failed, but this just punts on failure with no message.
The `which` letting the OS figure out where `udevadm` is located.

**Comment by k5okc** [comment]
> Sorry, can you clarify if postinst is actually _failing_ (and preventing package install) or if this is just a cosmetic issue?

I assumed it failed when I got an error message, but now I think the error message was just noise, and the installation was successful. It just didn't trigger.

I'll close the issue.
